name: ci pipeline

on:
#triggers the workflow push events and any branches that u will include here
  push:
    branches: ["main"]

  workflow_dispatch:
  #allows u to run this workflow manually from the action tab
jobs: 
#single deploy job 
  build:
    runs-on: ubuntu-latest
    steps:
      - name:checkout
      - uses: actions/checkout@v3
      - name: run one time script 
      - run: echo, Hello World!